### ISSUE TITLE
Still maintaining?

### ISSUE THREAD

**Issue by hellofantastic** [arnthor3/react-funnelchart#1]
Hey came across this and looks like a nice start to something that doesn't seem to exist for react.
I have been using react for about 3 months only using create-react-app so I'm fairly noobish on some of the details of tooling.
I did a clone and tried to nom start it but no webpack-dev-server  found
is it a mater of just installing webpack-dev-server?

**Comment by hellofantastic** [comment]
OKay caught my oversight I needed  to npm install after cloning...( head smack )
Will you be adding this to npm repository?

**Comment by hellofantastic** [comment]
Some linting issues too with __data__ no-underscore-dangle 
animationEase prop vaildation
animatationTime spelling and prop vaildation

**Comment by arnthor3** [comment]
Yes, I had some ideas on how to finish this one up but I got caught up in other projects. I will try to add this on my todo list and finish this one off as soon as possible.

**Comment by hellofantastic** [comment]
Okay @arnthor3 , thanks for responding... 
Currently due to time constraints I wrote a wrapper react component to use d3-funnel ([https://github.com/jakezatecky/d3-funnel](https://github.com/jakezatecky/d3-funnel))
Works alright.. will circle back
